version: 0.0.1
# version: ${ENV_VARIABLE_VERSION:- 0.0.1}

# Change default server ports
server:
  applicationConnectors:
    - type: http
      port: 9000
  adminConnectors:
    - type: http
      port: 9001
logging:
  level: INFO
  appenders:
    - type: console
      threshold: ALL
      queueSize: 512
      discardingThreshold: 0
      timeZone: UTC
      target: stdout
#      logFormat: "%-5p [%d{ISO8601,UTC}] %c: %m%n%dwREx"


#You can choose the user and password what you want.
mongoDBConnection:
  credentials:
    username: "admin"
    password: "password"
  seeds:
    - host: "localhost"
      port: 27017
  database: "dw_template_mongo"

database:
  # the name of the JDBC driver, mysql in our case
  driverClass: com.mysql.cj.jdbc.Driver
  # the username
  user: root
  # the password
  password:
  # the JDBC URL; the database is called dw_template
  url: jdbc:mysql://localhost:3306/dw_template?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC

  # any properties specific to your JDBC driver:
#  properties:
#    charSet: UTF-8
#    hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

  # the maximum amount of time to wait on an empty pool before throwing an exception
  maxWaitForConnection: 1s

  # the SQL query to run when validating a connection's liveness
  validationQuery: "/* MyApplication Health Check */ SELECT 1"

  # the minimum number of connections to keep open
  minSize: 8

  # the maximum number of connections to keep open
  maxSize: 32

  # whether or not idle connections should be validated
  checkConnectionWhileIdle: false